// src-electron/electron-preload.js
import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('db', {
  addDocument: (documentData) => ipcRenderer.invoke('add-document', documentData),
  addEvidence: (evidenceData) => ipcRenderer.invoke('add-evidence', evidenceData),
  addReference: (referenceData) => ipcRenderer.invoke('add-reference', referenceData),
  addStatement: (statementData) => ipcRenderer.invoke('add-statement', statementData),
  deleteDocument: (id) => ipcRenderer.invoke('delete-document', id),
  deleteEvidence: (id) => ipcRenderer.invoke('delete-evidence', id),
  deleteReference: (id) => ipcRenderer.invoke('delete-reference', id),
  deleteStatement: (id) => ipcRenderer.invoke('delete-statement', id),
  exportDocumentAsMarkdown: (id) => ipcRenderer.invoke('export-document-as-markdown', id),
  getAllDocuments: () => ipcRenderer.invoke('get-all-documents'),
  getAllEvidence: () => ipcRenderer.invoke('get-all-evidence'),
  getAllReferences: () => ipcRenderer.invoke('get-all-references'),
  getAllStatements: () => ipcRenderer.invoke('get-all-statements'),
  getAllStatementsForLinking: () => ipcRenderer.invoke('get-all-statements-for-linking'),
  getDocumentDetails: (id) => ipcRenderer.invoke('get-document-details', id),
  getEvidenceDetails: (id) => ipcRenderer.invoke('get-evidence-details', id),
  getReferenceDetails: (id) => ipcRenderer.invoke('get-reference-details', id),
  getStatementDetails: (id) => ipcRenderer.invoke('get-statement-details', id),
  linkEvidenceToStatement: (linkData) => ipcRenderer.invoke('link-evidence-to-statement', linkData),
  linkStatementsToDocument: (linkData) => ipcRenderer.invoke('link-statements-to-document', linkData),
  unlinkEvidenceFromStatement: (linkData) => ipcRenderer.invoke('unlink-evidence-from-statement', linkData),
  updateDocument: (docData) => ipcRenderer.invoke('update-document', docData),
  updateEvidence: (evidenceData) => ipcRenderer.invoke('update-evidence', evidenceData),
  updateReference: (referenceData) => ipcRenderer.invoke('update-reference', referenceData),
  updateStatement: (statementData) => ipcRenderer.invoke('update-statement', statementData),
});